### ISSUE TITLE
visual studio 2019 sdl2.sln 빌드시 C1083 intrin.h 오류

### ISSUE THREAD

**Issue by DooDooPark** [pdpdds/yuzaos#3]
``문제발생)

thirdparty/SDL/SDL2/SDL2.sln 

빌드시 

c1083  intrin.h 폴더와 파일을 읽을 수 없음의 오류 발생

솔루션)

thirdparty/SDL/SDL2/SDL/src/atomic/SDL_atomi.c 파일의

26번째줄 

#include <intrin.h> 를 주석 처리한 후 솔루션 다시 빌드를 통해 문제 해결.

빌드 환경)
Windows 10 
버전 20H2(OS 빌드 19042.1110)

visual studio community 2019 v.16.5.4
visual c++ 2019 - 00435-60000-00000-AA528

**Comment by pdpdds** [comment]
수정완료하였습니다. 감사합니다.
